"""relate user to shoes

Revision ID: 8ede1d0ac53f
Revises: 16bc6113a1b5
Create Date: 2026-02-23 23:30:03.751094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8ede1d0ac53f'
down_revision: Union[str, Sequence[str], None] = '16bc6113a1b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shoes', sa.Column('user_uid', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'shoes', 'user', ['user_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shoes', type_='foreignkey')
    op.drop_column('shoes', 'user_uid')
    # ### end Alembic commands ###
